# config/service.yaml
postgres:
  database: server_test
  user: patrick
  password:
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5
telegram:
  token: '1054426026:AAE-QWcn68QB3eEaZ_H-F37CnXsRmGemkDY'
  user_id:

